<a href="https://colab.research.google.com/github/Danil1D/Machine-learning/blob/main/%D0%94%D0%B0%D1%88%D0%BA%D0%B5%D0%B2%D0%B8%D1%87_%D0%BB%D0%B0%D0%B1%E2%84%964(%D0%B7%D0%B0%D0%B2%D0%B4_1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

data = load_breast_cancer()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target

#2. Проведіть попередній аналіз даних:
#1. Перегляд перших кількох рядків
print("Перегляд перших кількох рядків \n")
print(df.head())
#2. Перевірка назв стовпців та типів даних
print('Перевірка назв стовпців та типів даних\n')
print(df.info())

#3. Перевірка наявності пропущених значень
print(" Перевірка наявності пропущених значень\n")
print(df.isnull().sum())

#4. Дослідження розміру даних
print("Дослідження розміру даних\n")
print(df.shape)


Перегляд перших кількох рядків 

   mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perime

In [30]:
data = load_breast_cancer()
X = data.data
y = data.target
#2. Побудова і налаштування моделей
# 1. Розділення даних на навчальний і тестовий набори
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


#2. Побудуйте три моделі класифікації (на власний вибір)
models = {
    "Logistic Regression": LogisticRegression(max_iter=10000),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier()
}

param_grids = {
    "Logistic Regression": {
        'C': [0.1, 1, 10],
        'solver': ['lbfgs', 'liblinear']
    },
    "Decision Tree": {
        'max_depth': [3, 5, 10, None],
        'min_samples_split': [2, 5, 10]
    },
    "Random Forest": {
        'n_estimators': [50, 100, 200],
        'max_depth': [3, 5, 10, None]
    }
}



In [31]:
#3. Підберіть оптимальні параметри для кожної моделі за допомогою GridSearchCV (можна вибрати інший оптимізатор).
best_models = {}
for name, model in models.items():
    grid_search = GridSearchCV(model, param_grids[name], cv=5, scoring='accuracy', n_jobs=-1)
    grid_search.fit(X_train, y_train)
    best_models[name] = grid_search.best_estimator_
    print(f"Найкращі параметри для {name}: {grid_search.best_params_}")



Найкращі параметри для Logistic Regression: {'C': 10, 'solver': 'liblinear'}
Найкращі параметри для Decision Tree: {'max_depth': 5, 'min_samples_split': 2}
Найкращі параметри для Random Forest: {'max_depth': 10, 'n_estimators': 100}


In [32]:
# 4. Оцінка моделей
for name, model in best_models.items():
    print(f"\nМодель: {name}")
    y_pred = model.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    print(f"Точність: {accuracy:.4f}")

    print("Матриця помилок:")
    print(confusion_matrix(y_test, y_pred))

    print("Звіт про класифікацію:")
    print(classification_report(y_test, y_pred))





Модель: Logistic Regression
Точність: 0.9649
Матриця помилок:
[[ 60   3]
 [  3 105]]
Звіт про класифікацію:
              precision    recall  f1-score   support

           0       0.95      0.95      0.95        63
           1       0.97      0.97      0.97       108

    accuracy                           0.96       171
   macro avg       0.96      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171


Модель: Decision Tree
Точність: 0.9532
Матриця помилок:
[[ 59   4]
 [  4 104]]
Звіт про класифікацію:
              precision    recall  f1-score   support

           0       0.94      0.94      0.94        63
           1       0.96      0.96      0.96       108

    accuracy                           0.95       171
   macro avg       0.95      0.95      0.95       171
weighted avg       0.95      0.95      0.95       171


Модель: Random Forest
Точність: 0.9708
Матриця помилок:
[[ 59   4]
 [  1 107]]
Звіт про класифікацію:
              precision    reca

In [33]:
# 5. Прогнозування і висновки
best_model_name = max(best_models, key=lambda name: accuracy_score(y_test, best_models[name].predict(X_test)))
best_model = best_models[best_model_name]
print(f"\nНайкраща модель: {best_model_name}")

y_pred_best = best_model.predict(X_test)

print(f"\nРезультати прогнозування для найкращої моделі ({best_model_name}):")
print(y_pred_best)


Найкраща модель: Random Forest

Результати прогнозування для найкращої моделі (Random Forest):
[1 0 0 1 1 0 0 0 0 1 1 0 1 0 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0
 1 0 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 0 0 1 1 1 0 0 1 1 0 0 1 0
 1 1 1 1 1 1 0 1 1 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 1 1 0 1 1 0
 1 1 0 1 0 1 1 1 0 1 1 1 0 1 0 0 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0 1 1 0 1 0 0
 0 1 0 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1]
