<a href="https://colab.research.google.com/github/Danil1D/Machine-learning/blob/main/%D0%94%D0%B0%D1%88%D0%BA%D0%B5%D0%B2%D0%B8%D1%87_%D0%BB%D0%B0%D0%B1%E2%84%961_%D0%B2%D0%B0%D1%80%D1%96%D0%B0%D0%BD%D1%82_%E2%84%968.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Завдання 1.
Створіть одновимірний масив (вектор) зі спадаючою послідовністю чисел, де кожне наступне число менше попереднього на 2, починаючи з 30, та виведіть його значення.

In [2]:
import numpy as np

vector = np.arange(30, -2, -2)

vector


array([30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

Завдання 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями факторіалів натуральних чисел, починаючи з 1, та виведіть його значення.

In [3]:
import numpy as np
import math

factorials = [math.factorial(i) for i in range(1, 10)]

matrix = np.array(factorials).reshape(3, 3)

matrix


array([[     1,      2,      6],
       [    24,    120,    720],
       [  5040,  40320, 362880]])

Завдання 3. Створіть масив розміром 4x4, заповніть його випадковими цілими числами від 1 до 10 та виведіть його значення.

In [4]:
random_matrix = np.random.randint(1, 11, size=(4, 4))

random_matrix


array([[ 4,  8,  4,  7],
       [ 4, 10,  5,  5],
       [ 2,  6,  2,  3],
       [ 3,  7, 10,  2]])

Завдання 4. Створіть масив розміром 6x6, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та обчисліть суму всіх діагональних елементів.

In [7]:
import numpy as np

matrix = np.random.uniform(0, 1, (6, 6))

main_diagonal_sum = np.trace(matrix)

anti_diagonal_sum = np.trace(np.fliplr(matrix))

total_diagonal_sum = main_diagonal_sum + anti_diagonal_sum - matrix[2, 2]

print("Matrix:")
print(matrix)
print("Sum of main diagonal elements:", main_diagonal_sum)
print("Sum of anti-diagonal elements:", anti_diagonal_sum)
print("Total sum of diagonal elements:", total_diagonal_sum)

Matrix:
[[0.12573401 0.88639021 0.29242504 0.03251596 0.27156027 0.8704827 ]
 [0.82963558 0.01822747 0.42251586 0.04520175 0.3552077  0.45236402]
 [0.55029059 0.98765298 0.55640069 0.8272628  0.8694888  0.43036884]
 [0.70109789 0.97659015 0.81825432 0.71140824 0.8609771  0.80068397]
 [0.69035835 0.31900217 0.33004438 0.92661374 0.63684376 0.54517125]
 [0.87979277 0.252334   0.75542266 0.37801751 0.36827772 0.76991649]]
Sum of main diagonal elements: 2.8185306638201286
Sum of anti-diagonal elements: 4.0700024482333985
Total sum of diagonal elements: 6.332132425846516


Завдання 5. Створіть два одновимірних масиви розміром 4, заповніть їх випадковими дійсними числами від -10 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [8]:
import numpy as np

array1 = np.random.uniform(-10, 10, 4)
array2 = np.random.uniform(-10, 10, 4)

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print("Array 1:", array1)
print("Array 2:", array2)
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)


Array 1: [ 1.7095399  -6.19711856 -3.19596282  4.91864149]
Array 2: [-4.62242943  6.66138525 -5.85156229  3.15117109]
Addition: [-2.91288953  0.46426669 -9.04752511  8.06981258]
Subtraction: [  6.33196934 -12.85850381   2.65559947   1.7674704 ]
Multiplication: [ -7.90222756 -41.28139418  18.7013755   15.49948088]


Завдання 6. Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 1 до 5 та знайдіть їх добуток.

In [9]:
import numpy as np

matrix1 = np.random.randint(1, 6, (4, 4))
matrix2 = np.random.randint(1, 6, (4, 4))

product = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nProduct of Matrix 1 and Matrix 2:")
print(product)


Matrix 1:
[[2 2 1 2]
 [1 1 3 1]
 [3 4 5 5]
 [2 4 5 4]]

Matrix 2:
[[4 1 1 1]
 [4 5 3 1]
 [2 2 5 2]
 [4 5 4 2]]

Product of Matrix 1 and Matrix 2:
[[26 24 21 10]
 [18 17 23 10]
 [58 58 60 27]
 [50 52 55 24]]


Завдання 7. Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 4 та перемножте їх між собою.

In [10]:
import numpy as np

matrix1 = np.random.randint(1, 5, (2, 3))

matrix2 = np.random.randint(1, 5, (3, 3))

product = np.dot(matrix1, matrix2)

# Виведення результатів
print("Matrix 1 (2x3):")
print(matrix1)
print("\nMatrix 2 (3x3):")
print(matrix2)
print("\nProduct of Matrix 1 and Matrix 2:")
print(product)


Matrix 1 (2x3):
[[4 1 3]
 [1 1 1]]

Matrix 2 (3x3):
[[1 2 1]
 [3 3 4]
 [3 3 1]]

Product of Matrix 1 and Matrix 2:
[[16 20 11]
 [ 7  8  6]]


Завдання 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 7 та знайдіть її обернену матрицю.

In [11]:
import numpy as np

matrix = np.random.randint(1, 8, (3, 3))

print("Matrix:")
print(matrix)

if np.linalg.det(matrix) != 0:
    inverse_matrix = np.linalg.inv(matrix)
    print("\nInverse Matrix:")
    print(inverse_matrix)
else:
    print("\nThe matrix is singular and does not have an inverse.")


Matrix:
[[4 1 2]
 [5 5 5]
 [4 3 7]]

Inverse Matrix:
[[ 0.36363636 -0.01818182 -0.09090909]
 [-0.27272727  0.36363636 -0.18181818]
 [-0.09090909 -0.14545455  0.27272727]]


Завдання 9. Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від -5 до 5 та транспонуйте її.

In [12]:
import numpy as np

matrix = np.random.uniform(-5, 5, (5, 5))

transposed_matrix = np.transpose(matrix)

print("Original Matrix (5x5):")
print(matrix)
print("\nTransposed Matrix (5x5):")
print(transposed_matrix)


Original Matrix (5x5):
[[-0.57888077  4.59543094  1.44494474 -2.55102958  2.39099533]
 [-1.45890798 -1.38212552 -0.11958377  2.89699124 -4.62571707]
 [-2.71016834 -1.5107572  -0.45828823  1.91660573 -0.17935005]
 [-2.79219816  4.50148661  4.00895773  2.16406058 -1.84363433]
 [-2.44627124  1.6093902  -3.46007063 -0.51534928 -0.58042086]]

Transposed Matrix (5x5):
[[-0.57888077 -1.45890798 -2.71016834 -2.79219816 -2.44627124]
 [ 4.59543094 -1.38212552 -1.5107572   4.50148661  1.6093902 ]
 [ 1.44494474 -0.11958377 -0.45828823  4.00895773 -3.46007063]
 [-2.55102958  2.89699124  1.91660573  2.16406058 -0.51534928]
 [ 2.39099533 -4.62571707 -0.17935005 -1.84363433 -0.58042086]]


Завдання 10. Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1 і знайдіть добуток матриці на вектор.

In [13]:
import numpy as np

matrix = np.random.randint(1, 11, (3, 4))

vector = np.random.uniform(0, 1, (4, 1))

product = np.dot(matrix, vector)

print("Matrix (3x4):")
print(matrix)
print("\nVector (4x1):")
print(vector)
print("\nProduct of Matrix and Vector:")
print(product)


Matrix (3x4):
[[ 4  5  1 10]
 [ 2  7 10  6]
 [ 4  7  1  3]]

Vector (4x1):
[[0.54945233]
 [0.21048378]
 [0.3220407 ]
 [0.63487631]]

Product of Matrix and Vector:
[[9.92103202]
 [9.60195599]
 [5.89786542]]


Завдання 11. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.

In [14]:
import numpy as np

matrix = np.random.uniform(0, 1, (2, 3))

vector = np.random.uniform(0, 1, (3, 1))

product = np.dot(matrix, vector)

print("Matrix (2x3):")
print(matrix)
print("\nVector (3x1):")
print(vector)
print("\nProduct of Matrix and Vector:")
print(product)


Matrix (2x3):
[[0.48733488 0.67698047 0.25948188]
 [0.2829007  0.85894276 0.86424272]]

Vector (3x1):
[[0.43740605]
 [0.01128153]
 [0.78379633]]

Product of Matrix and Vector:
[[0.42418155]
 [0.81082294]]


Завдання 12. Створіть дві матриці розміром 9x9, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть відношення елементів другої матриці до першої (поелементне ділення).

In [15]:
import numpy as np

matrix1 = np.random.randint(1, 11, (9, 9))
matrix2 = np.random.randint(1, 11, (9, 9))

ratio = matrix2 / matrix1

# Виведення результатів
print("Matrix 1 (9x9):")
print(matrix1)
print("\nMatrix 2 (9x9):")
print(matrix2)
print("\nRatio of Matrix 2 to Matrix 1:")
print(ratio)


Matrix 1 (9x9):
[[10  3  3  3  9  7  7 10  8]
 [ 6 10  9  5  2  7  4  1  2]
 [ 3  3  8  1  9  3  9  6  4]
 [ 9  7  9  4  5  4  9 10  8]
 [ 9  3  5  9  8  3  6  4  8]
 [ 5  6  5  9  9  5 10  6  3]
 [ 9  5 10  3 10  1  3 10  9]
 [ 8  8  4  6  1 10  5  9  5]
 [ 3  3  5  2  8  4  3  6  3]]

Matrix 2 (9x9):
[[ 3  9  1  4  2  2  5  7  6]
 [ 1  9  6  2  2  2  5  6  9]
 [ 9  5  6  6  9  1  7  7  2]
 [ 1  2  3  5  6  1 10  3  4]
 [ 7  5  8  7  6  5 10  2  6]
 [ 6  1  3  4  6  5  7  8  6]
 [ 5  7  1  4  3 10  7  9  5]
 [ 3  5  2  6  2  5 10  1  6]
 [10  7 10  8  5  3 10  3  8]]

Ratio of Matrix 2 to Matrix 1:
[[ 0.3         3.          0.33333333  1.33333333  0.22222222  0.28571429
   0.71428571  0.7         0.75      ]
 [ 0.16666667  0.9         0.66666667  0.4         1.          0.28571429
   1.25        6.          4.5       ]
 [ 3.          1.66666667  0.75        6.          1.          0.33333333
   0.77777778  1.16666667  0.5       ]
 [ 0.11111111  0.28571429  0.33333333  1.25        1.2

Завдання 13. Створіть дві матриці розміром 9x9, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та знайдіть їх добуток.

In [16]:
import numpy as np

matrix1 = np.random.randint(1, 6, (9, 9))
matrix2 = np.random.randint(1, 6, (9, 9))

product = matrix1 * matrix2

print("Matrix 1 (9x9):")
print(matrix1)
print("\nMatrix 2 (9x9):")
print(matrix2)
print("\nElement-wise Product of Matrix 1 and Matrix 2:")
print(product)


Matrix 1 (9x9):
[[2 1 1 5 3 3 3 3 2]
 [5 1 3 4 2 5 4 4 5]
 [5 4 2 1 4 4 2 1 2]
 [1 3 2 5 5 3 1 3 4]
 [1 1 4 1 1 5 3 1 2]
 [5 2 3 2 1 3 2 2 4]
 [4 2 4 1 5 3 5 5 4]
 [5 2 3 2 2 3 4 2 3]
 [4 5 1 5 4 5 1 2 5]]

Matrix 2 (9x9):
[[2 2 3 2 2 2 3 3 2]
 [3 2 2 2 4 3 2 3 3]
 [3 3 5 3 3 2 1 3 2]
 [4 1 1 4 1 4 2 5 2]
 [5 4 3 3 1 2 3 5 1]
 [4 3 2 5 3 2 1 4 5]
 [3 5 3 1 5 4 3 4 2]
 [1 4 4 3 1 3 4 1 3]
 [1 4 4 3 4 5 1 3 2]]

Element-wise Product of Matrix 1 and Matrix 2:
[[ 4  2  3 10  6  6  9  9  4]
 [15  2  6  8  8 15  8 12 15]
 [15 12 10  3 12  8  2  3  4]
 [ 4  3  2 20  5 12  2 15  8]
 [ 5  4 12  3  1 10  9  5  2]
 [20  6  6 10  3  6  2  8 20]
 [12 10 12  1 25 12 15 20  8]
 [ 5  8 12  6  2  9 16  2  9]
 [ 4 20  4 15 16 25  1  6 10]]


Завдання 14. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від -5 до 5 та знайдіть середнє арифметичне значення елементів матриці.

In [17]:
import numpy as np

matrix = np.random.randint(-5, 6, (3, 3))

mean_value = np.mean(matrix)

print("Matrix (3x3):")
print(matrix)
print("\nMean value of the elements:")
print(mean_value)


Matrix (3x3):
[[-2  2  0]
 [-2  3  1]
 [ 0 -3  3]]

Mean value of the elements:
0.2222222222222222


Завдання 15. Створіть матрицю розміром 10x10, заповніть її випадковими дійсними числами в діапазоні від -2 до 2 та знайдіть вектор-стовпчик, що містить найменше за модулем значення елементу у кожному рядку матриці.

In [18]:
import numpy as np

matrix = np.random.uniform(-2, 2, (10, 10))

min_abs_values = np.min(np.abs(matrix), axis=1)

print("Matrix (10x10):")
print(matrix)
print("\nVector of minimum absolute values in each row:")
print(min_abs_values)


Matrix (10x10):
[[ 0.67341967  1.56461615 -1.71044012  1.4905333  -0.01187179 -1.68495322
   0.71300572  1.43147937  0.20452016  1.68002027]
 [ 0.92383296  0.79097852  0.9294313   1.487858    1.10945293  0.32286908
   0.77061067  1.5154242  -0.40692828  1.70486737]
 [ 0.75988372  0.91525662 -0.97631927 -1.82248659 -0.52838752  1.20849707
  -0.23893052 -1.93283389  0.70349792  1.93076861]
 [-1.0509183  -0.8014107  -0.61742857 -1.57247313 -1.08793743 -1.93245314
  -0.7123314   0.66537304  0.31608778 -0.83385628]
 [ 0.0829515   0.6537894   0.73093866 -0.38086518 -1.26267453  1.59881076
  -0.84492081  0.32265354 -0.02738677  1.81326301]
 [ 1.54436995 -1.85943312  0.70250036  0.28335859 -1.09451153  1.63028706
  -0.37975446  0.70012461  0.55141741  1.51853572]
 [-1.21604432  1.53296706 -1.39995169  0.93818423  0.83363868 -1.295929
   0.19517472  1.35434129  0.66666351 -0.44028606]
 [ 0.92772027  0.66078188 -0.77005467  1.53228612 -1.20688601  0.85934397
  -0.74492256  0.68719921 -1.95699565

Я навчився створювати різні матриці, використовуючи numpy. Завдання включали поелементні операції, обчислення оберненої матриці, транспонування, а також аналіз статистичних характеристик, таких як середнє арифметичне та мінімальні значення за модулем. Це показує, як ефективно використовувати бібліотеку для математичних обчислень та аналізу даних.